## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.random.rand(10) * 10
arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 8.65779315, -7.1029686 ,  9.50910819, -4.2118263 ,  9.04765674,
       -7.03714486,  1.7492576 , -3.4593395 ,  9.79066098, -3.93797203])

**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = np.random.rand(10) * 100
max_index = arr.argmax()
arr[max_index] = 0
arr, max_index

(array([ 0.        , 77.06274166, 66.30699983, 38.5853465 , 78.40781695,
        59.47396403, 96.53902999, 48.00581686, 75.40102325, 84.91405554]),
 0)

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
def direct_mul(array):
    shape = map(len, array)
    ix = np.indices(shape, dtype=int)
    #print(ix)
    ix = ix.reshape(len(array), -1).T
    #print(ix)

    for n, arr in enumerate(array):
        ix[:, n] = array[n][ix[:, n]] 

    return ix

arr = np.array([[15, 18, 21],
                [42, 54, 66]])
print(direct_mul(arr))


[[15 42]
 [15 54]
 [15 66]
 [18 42]
 [18 54]
 [18 66]
 [21 42]
 [21 54]
 [21 66]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [15]:
A = np.array([[1, 8, 6], #true
              [5, 4, 1], #false
              [3, 3, 3], #false
              [6, 8, 1], #true
              [4, 10, 5],#false
              [3, 5, 9], #true
              [4, 10, 9],#false
              [7, 7, 7]])#false

B = np.array([[5, 1],
              [6, 3]])

# Создаем новый массив, содержащий True, если каждая строка в A содержит элементы из каждой строки в B
isin_arr = np.logical_and.reduce([np.isin(A, B[i]).any(axis=1) for i in range(B.shape[0])])
print(isin_arr)
# Используем isin_arr для индексации массива A и получения нужных строк
result = A[isin_arr]
print(result)


[ True False False  True False  True False False]
[[1 8 6]
 [6 8 1]
 [3 5 9]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
arr = np.array([[1, 1, 1],
                [5, 4, 1],
                [3, 3, 3],
                [6, 8, 1],
                [4, 10, 5],
                [4, 5, 9],
                [4, 10, 9],
                [7, 7, 7],
                [2, 2, 10],
                [3, 2, 1]])

not_same_value_rows = [row for row in arr if not np.all(row == row[0])]

print(np.array(not_same_value_rows))

[[ 5  4  1]
 [ 6  8  1]
 [ 4 10  5]
 [ 4  5  9]
 [ 4 10  9]
 [ 2  2 10]
 [ 3  2  1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [88]:
arr = np.array([[2, 0, 0], [2, 1, 1], [2, 1, 1], [2, 3, 0], [2, 3, 0]])
unique_arr = np.unique(arr, axis=0)
unique_arr

array([[2, 0, 0],
       [2, 1, 1],
       [2, 3, 0]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [96]:
X = np.array([[1, 0, 1], 
              [2, 0, 2], 
              [3, 0, 3], 
              [4, 4, 4]])

diag_X = np.diag(X)
nonzero_indices = np.nonzero(diag_X)
nonzero_elements = diag_X[nonzero_indices]
product_numpy = np.prod(nonzero_elements)
print(product_numpy) 


# без numpy
X = [[1, 0, 1], 
     [2, 0, 2], 
     [3, 0, 3], 
     [4, 4, 4]]
product = 1

# для того, чтобы итерироваться по диагонали нужно понять больше там строк или столбцов
for i in range(min(len(X), len(X[0]))):
    if X[i][i] != 0:
        product *= X[i][i]
print(product) 

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [16]:
# c numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result_numpy = np.array_equal(np.sort(x), np.sort(y))
print(result_numpy)

# без numpy
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

result = sorted(x) == sorted(y)
print(result)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [17]:
# c numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def max_after_zero_n(x):
    indices = np.where(x[:-1] == 0)[0]
    if len(indices) == 0:
        return None
    else:
        return np.max(x[indices+1])
result = max_after_zero_n(x)
print(result)

# без numpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def max_after_zero(x):
    maxs = -1
    for i, num in enumerate(x[:-1]):
        if num == 0 and x[i+1] > maxs:
            maxs = x[i+1]
    return maxs
result = max_after_zero(x)
print(result)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [93]:
# c numpy 
x = np.array([2, 2, 2, 3, 3, 3, 5])
unique, counts = np.unique(x, return_counts=True)
x = np.array([2, 2, 2, 3, 3, 3, 5])
result = (unique, counts)
print(result)

# без numpy
x = [2, 2, 2, 3, 3, 3, 5]
first_arr = sorted(set(x))
result = (first_arr, [x.count(num) for num in first])
print(result)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [28]:
import numpy as np
from scipy.spatial.distance import cdist
from timeit import timeit

# генерируе выборки
X = np.random.rand(1000, 10)
Y = np.random.rand(500, 10)

# вычисляем матрицу расстояний с помощью сайпай
dist_matrix = cdist(X, Y)
# вычисляем матрицу расстояний через нампай
def matrix_evcl(X, Y):
    dist_matrix = np.zeros((X.shape[0], Y.shape[0]))
    for i, x in enumerate(X):
        for j, y in enumerate(Y):
            dist_matrix[i, j] = np.sqrt(np.sum((x - y) ** 2))
    return dist_matrix

# сравниваем скорость работы двух методов
n = 5
t1 = timeit(lambda: cdist(X, Y), number=n)
t2 = timeit(lambda: matrix_evcl(X, Y), number=n)
print(f"Время работы cdist: {t1/n:.5f} секунд")
print(f"Время работы циклов: {t2/n:.5f} секунд")


Время работы cdist: 0.01243 секунд
Время работы циклов: 5.84913 секунд


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [49]:
import numpy as np

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [53]:
calorie_stats = np.loadtxt("./cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [55]:
average_calories = np.mean(calorie_stats) - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [56]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [57]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [65]:
nth_percentile = np.percentile(calorie_stats, q = [4, 50])
nth_percentile[0]

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [74]:
more_calories = calorie_stats[calorie_stats > 60].shape[0] / calorie_stats.shape[0]
more_calories

0.961038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [75]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [77]:
# В рамках маркетинга можно ипользовать факт о том, что данный продукт является менее каллорийным, чем 96% продуктов
# этого же сегмента на рынке. Также в пользу этого аргумента говорит высокое стандартное отклонение.